import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function CSP() {
  return (
    <>
      <Head>
        <title>CSP Lab - default-src</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
        <h1>
          Which directives fallback to <strong>default-src</strong>?
        </h1>
        <ol>
          <li>script-src</li>
          <li>style-src</li>
          <li>font-src</li>
          <li>img-src</li>
          <li>connect-src</li>
          <li>worker-src</li>
          <li>object-src</li>
          <li>media-src</li>
          <li>manifest-src</li>
          <li>frame-src</li>
          <li>prefetch-src</li>
          <li>child-src</li>
        </ol>
        <h1>
          Which directives <strong>DO NOT</strong> fallback to{" "}
          <strong>default-src</strong>?
        </h1>
        <ol>
          <li>base-uri</li>
          <li>form-action</li>
          <li>frame-ancestors</li>
          <li>report-uri</li>
          <li>sandbox</li>
        </ol>
      </main>
    </>
  );
}
