import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function CSP() {
  return (
    <>
      <Head>
        <title>CSP Lab - font-src/origin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          httpEquiv="Content-Security-Policy"
          content="font-src http://localhost:3000"
        ></meta>
      </Head>
      <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
        <code>
          {`> <meta http-equiv='Content-Security-Policy' content="font-src localhost:3000" ></meta>`}
        </code>
        只需設定 host，且 protocol 必須要是 https
      </main>
    </>
  );
}
