import Head from 'next/head'
import Link from "next/link";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Page() {
  return (
    <>
      <Head>
        <title>CSP Lab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.grid}>
          <li className={styles.card}>
            <Link href="/csp">
              <h2>
                CSP <span>-&gt;</span>
              </h2>
              <p>
                The lab for the <strong>Content Security Policy</strong>.
              </p>
            </Link>
          </li>
        </ul>
      </main>
    </>
  );
}
