import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function CSP() {
  return (
    <>
      <Head>
        <title>CSP Lab - script-src</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
        <h1>Rules</h1>
        <ul className={styles.grid}>
          <li className={styles.card}>
            <Link href="script-src/none">
              <h2>
                none <span>-&gt;</span>
              </h2>
              <p>不允許任何 script 的執行</p>
            </Link>
          </li>
          <li className={styles.card}>
            <a href="script-src/self">
              <h2>
                self <span>-&gt;</span>
              </h2>
              <p>只允許 same-origin 的資源</p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="script-src/origin">
              <h2>
                特定 origin <span>-&gt;</span>
              </h2>
              <p>允許特定 origin（只允許 HTTPS）</p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="script-src/nonce">
              <h2>
                nonce<span>-&gt;</span>
              </h2>
              <p>在後端產生一個隨機字串，有帶上的 script 標籤就可以載入：</p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="script-src/others">
              <h2>
                others <span>-&gt;</span>
              </h2>
              <p>其他規則</p>
            </a>
          </li>
        </ul>
      </main>
    </>
  );
}
