import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function CSP() {
    return (
      <>
        <Head>
          <title>CSP Lab - script-src/nonce</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <meta
            http-equiv="Content-Security-Policy"
            content="script-src 'self' 'unsafe-eval' 'nonce-ilovepinkoi'"
          ></meta>
        </Head>
        <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
          <code>
            {`> <meta http-equiv='Content-Security-Policy' content="script-src 'self' 'nonce-ilovepinkoi"' ></meta>`}
          </code>
          <script
            nonce="ilovepinkoi"
            src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.3/angular.min.js"
          ></script>
        </main>
      </>
    );
}
