import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function CSP() {
  return (
    <>
      <Head>
        <title>CSP Lab - script-src/origin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          httpEquiv="Content-Security-Policy"
          content="script-src 'self' 'unsafe-eval' cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js www.google-analytics.com *.facebook.net;"
        ></meta>
      </Head>
      <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
        <code>
          {`> <meta http-equiv='Content-Security-Policy' content="script-src cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js" ></meta>`}
        </code>
        <code>
          {`> <meta http-equiv='Content-Security-Policy' content="script-src www.google-analytics.com *.facebook.net`}
        </code>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
      </main>
    </>
  );
}
