import { useEffect, useRef } from "react";
import Head from "next/head";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const Button = () => {
    const buttonRef = useRef<HTMLButtonElement>(null);
    
    useEffect(() => {
        const greeting = () =>
          window.alert("Happy Halloween!")
        ;

        if (buttonRef.current) {
            buttonRef.current.addEventListener("click", greeting);
        }

        // setTimeout('alert(1)') // 'unsafe-eval' 可執行
        
        return () => {
            if (buttonRef.current) {
                buttonRef.current.removeEventListener("click", greeting);
            }
        }
    }, []);

    return <button ref={buttonRef}>Rect Button</button>;
}

export default function CSP() {
  return (
    <>
      <Head>
        <title>CSP Lab - script-src/nonce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          http-equiv="Content-Security-Policy"
          content="script-src 'self' 'unsafe-eval'" // 'unsafe-eval' 在 Next 的開發環境下一定要設定
        ></meta>
      </Head>
      <main className={`${styles.main} ${styles.main__s} ${inter.className}`}>
        <code>
          {`> <meta http-equiv='Content-Security-Policy' content="script-src 'self' 'unsafe-inline'" ></meta>`}
        </code>
        <button id="button">Trick or treat！</button>
        <Script>
          {`
                window.alert('hello world');
            
                const button = document.getElementById('button');
                button.addEventListener('click', () => window.alert('Happy Halloween!'))
            `}
        </Script>

        <Button />
      </main>
    </>
  );
}
